/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    public void testAddNumbers() {
        Library classUnderTest = new Library();
        assertEquals(5, classUnderTest.addNumbers(2, 3));
    }

    @Test
    public void testAlwaysFailsToShowReportingOfTestFailures() {
        Library classUnderTest = new Library();
        assertEquals(4, classUnderTest.subtractNumbers(7, 3));
    }

    @Disabled
    @Test
    public void testIgnore() { /* To show reporting of ignored tests */ }

    @Test
    public void testAlwaysThrowsExceptionToShowReportingOfTestFailuresDueToException() throws Exception {
        throw new Exception();
    }
}
