/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.Ignore;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testAddNumbers() {
        Library classUnderTest = new Library();
        assertEquals(5, classUnderTest.addNumbers(2, 3));
    }

    @Test
    public void testAlwaysFailsToShowReportingOfTestFailures() {
        Library classUnderTest = new Library();
        assertEquals(4, classUnderTest.subtractNumbers(7, 3));
    }

    @Ignore
    @Test
    public void testIgnore() { /* To show reporting of ignored tests */ }

    @Test
    public void testAlwaysThrowsExceptionToShowReportingOfTestFailuresDueToException() throws Exception {
        throw new Exception();
    }
}
